GET http://localhost:8080/users HTTP/1.1

###

POST http://localhost:8080/users/create HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvbmhAaG90bWFpbC5jb20iLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTYyNTM1NTU5OCwiZXhwIjoxNjI1NDQxOTk4LCJzdWIiOiIwMjc3OGIwYS0xZWE2LTQ5MTAtYTc4Yy1hOTFhZjIzZGIyYmUifQ.jtxe4Pr7GyLJcP-tTfy50VzyWGeEAbwndzDXv5YfDsU

{
  "email": "john@hotmail.com",
  "name": "João",
  "admin": false,
  "password": "123abc"
}

###
POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
  "email": "admin",
  "password": "admin"
}

### Modules

GET http://localhost:8080/modules HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluIiwiYWRtaW4iOnRydWUsImlhdCI6MTYyNTQ5MDU5MywiZXhwIjoxNjI1NTc2OTkzLCJzdWIiOiJiNjg5NTg5My00MGU2LTRkNDQtOGFhMC0wZDI2YTVmM2ZmMzQifQ.iu4RW-8KWbnJ8fGv4uxsKjni6XZZ2-nUXShgWxOe0Fs

###

POST http://localhost:8080/modules/create HTTP/1.1
Content-Type: application/json

{
  "name": "Informática básica"
}

###

PUT http://localhost:8080/modules/9ecfc171-0fb9-443a-a8c5-34417a91dfe8/edit HTTP/1.1
Content-Type: application/json

{
  "name": "Informática avançada"
}

###

DELETE http://localhost:8080/modules/09828f33-38a6-4746-8593-4eb9a8877c7e/delete HTTP/1.1

### Classes

GET http://localhost:8080/classes HTTP/1.1

###

POST http://localhost:8080/classes/create HTTP/1.1
Content-Type: application/json

{
  "name": "Noções básicas de informática",
  "module": "9ecfc171-0fb9-443a-a8c5-34417a91dfe8",
  "start_date": "{{$datetime iso8601}}"
}

###
PUT http://localhost:8080/classes/6b40cd7c-4957-49f9-8f8b-6097808b82ef/edit HTTP/1.1
Content-Type: application/json

{
  "name": "Noções avançadas de informática"
}

###
DELETE http://localhost:8080/classes/6b40cd7c-4957-49f9-8f8b-6097808b82ef/delete