GET http://localhost:8080/users HTTP/1.1

###

POST http://localhost:8080/users/create HTTP/1.1
content-type: application/json
Authorization: "Bearer eyhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvYW9wZWRyb0Bob3RtYWlsLmNvbSIsImlhdCI6MTYyNTExMTU5MCwiZXhwIjoxNjI1MTk3OTkwLCJzdWIiOiIxNjYxYjM1MC03OGQ4LTQyYWMtYmUxMC1lYzM0NDAwMTgyOTIifQ.cv5lmLoi-UAQOXU6BUldQAICdXaMZXa3ph4QVYjGy7E

{
  "email": "joaopedro0128@hotmail.com",
  "name": "João",
  "admin": true,
  "password": "123abc"
}

###
POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
  "email": "joaopedro@hotmail.com",
  "password": "123abc"
}

### Modules

GET http://localhost:8080/modules HTTP/1.1

###

POST http://localhost:8080/modules/create HTTP/1.1
Content-Type: application/json

{
  "name": "Informática básica"
}

###

PUT http://localhost:8080/modules/09828f33-38a6-4746-8593-4eb9a8877c7e/edit HTTP/1.1
Content-Type: application/json

{
  "name": "Informática avançada"
}

###

DELETE http://localhost:8080/modules/09828f33-38a6-4746-8593-4eb9a8877c7e/delete HTTP/1.1